
-- Clear existing data
DELETE FROM pain_formula_vars;
DELETE FROM pain_library;

-- Insert 22 pains
INSERT INTO pain_library (pain_id, persona, sub_group, display_order, pain_statement, pain_statement_es, pain_statement_fr, pain_description, pain_description_es, pain_description_fr, trigger_phrases, primary_module, formula_expression, is_archived) VALUES
('P01', 'people_ops', 'time', 1,
 'Manual time tracking and labour compliance risk',
 'Control horario manual y riesgo de incumplimiento laboral',
 'Suivi du temps manuel et risque de conformité au droit du travail',
 'Manual time tracking consumes employee time daily and creates exposure to labour inspection penalties.',
 'El fichaje manual consume tiempo diario de los empleados y expone a sanciones por inspección laboral.',
 'Le suivi manuel du temps consomme du temps quotidien et expose à des sanctions lors d''inspections du travail.',
 'Prospect describes manual or paper-based attendance, distrust of hours data, labour-inspection worries, or admin time lost to time tracking. Sample phrases: "we use Excel for hours", "I''m afraid of a labour inspection", "clocking in is a mess", "I don''t really know what hours people work", "tracking time takes too long".',
 'Time Tracking', '(I19) * (I1) * (I7) * (I14 / 60)', false),

('P02', 'people_ops', 'inefficiency', 2,
 'Inefficient shift planning causes payroll waste',
 'Planificación ineficiente de turnos genera desperdicio en nómina',
 'Planification inefficace des postes entraîne du gaspillage salarial',
 'Spreadsheet-based scheduling drives over- and under-staffing, generating recurring payroll waste every week.',
 'La planificación en hojas de cálculo provoca sobre- y sub-dotación, generando desperdicio recurrente de nómina cada semana.',
 'La planification sur tableur entraîne un excès ou un manque de personnel, générant un gaspillage salarial récurrent chaque semaine.',
 'Prospect mentions overtime surprises, last-minute scheduling, shift swaps in WhatsApp, or scheduling done in Excel. Sample phrases: "shifts are planned in Excel", "we always blow the shift budget", "people complain about scheduling", "I never know if I''m under-staffed".',
 'Shifts', '(I20) * (I1) * (I14) * (I11)', false),

('P03', 'people_ops', 'direct_cost_saving', 3,
 'Fragmented training records and missed subsidies',
 'Registros de formación fragmentados y subvenciones no reclamadas',
 'Dossiers de formation fragmentés et subventions non réclamées',
 'Training data is scattered, blocking audit readiness and leaving available training subsidies and tax credits unclaimed.',
 'Los datos de formación están dispersos, impidiendo la preparación para auditorías y dejando sin reclamar subvenciones disponibles.',
 'Les données de formation sont dispersées, bloquant la conformité aux audits et laissant les subventions disponibles non réclamées.',
 'Prospect describes manual training records, lost certifications, audit pain, or unclaimed training subsidies. Sample phrases: "we don''t claim FUNDAE / OPCO", "I lose track of who''s certified", "training records are in folders", "audits are a nightmare".',
 'Trainings', '(I32) * (I1)', false),

('P04', 'people_ops', 'time', 4,
 'Manual training rollout and completion tracking',
 'Despliegue manual de formación y seguimiento de completitud',
 'Déploiement manuel des formations et suivi de complétion',
 'L&D and managers spend hours manually assigning, reminding and tracking training completion.',
 'L&D y managers dedican horas a asignar, recordar y hacer seguimiento de la finalización de formaciones.',
 'Les responsables L&D passent des heures à assigner, relancer et suivre la complétion des formations.',
 'Prospect describes chasing employees by email, low completion rates, no LMS or fragmented LMS. Sample phrases: "I send reminders by email", "no one finishes training", "we don''t have an LMS", "managers chase training manually".',
 'Trainings', '(I33) * (I9) * (I16)', false),

('P05a', 'people_ops', 'time', 5,
 'Manual training content creation',
 'Creación manual de contenido formativo',
 'Création manuelle de contenu de formation',
 'HR / L&D managers build courses, slides and materials from scratch instead of leveraging templates and AI-assisted authoring.',
 'Los managers de HR / L&D crean cursos y materiales desde cero en lugar de aprovechar plantillas y asistencia por IA.',
 'Les responsables RH / L&D construisent des cours et supports depuis zéro au lieu d''utiliser des modèles et l''assistance IA.',
 'Prospect describes building trainings from scratch in PowerPoint, no library of reusable content, long course-creation cycles. Sample phrases: "I build all our trainings in PowerPoint", "creating a course takes weeks", "we have no template library", "every training is built from scratch".',
 'Trainings', '(I48) * (I49) * (I16)', false),

('P05b', 'people_ops', 'time', 6,
 'Manual contract and document signing',
 'Firma manual de contratos y documentos',
 'Signature manuelle des contrats et documents',
 'Contracts, NDAs and policy updates are sent and signed manually, creating delays and audit gaps.',
 'Contratos, NDAs y actualizaciones de políticas se envían y firman manualmente, creando retrasos y vacíos de auditoría.',
 'Les contrats, NDA et mises à jour de politiques sont envoyés et signés manuellement, créant des retards et des lacunes d''audit.',
 'Prospect describes paper signatures, slow document workflows, missing NDAs, or DocuSign used as a side tool. Sample phrases: "we still print and sign", "contracts take days", "we use DocuSign on the side", "document trail is messy".',
 'Documents', '(I5) * (I34 / 60) * (I15)', false),

('P06', 'hr_director', 'time', 7,
 'Limited real-time visibility into HR data',
 'Visibilidad limitada en tiempo real de los datos de RRHH',
 'Visibilité limitée en temps réel des données RH',
 'HR data is spread across spreadsheets and emails, requiring significant manual effort to produce reliable reports.',
 'Los datos de RRHH están dispersos en hojas de cálculo y emails, requiriendo un esfuerzo manual significativo para producir informes fiables.',
 'Les données RH sont dispersées dans des tableurs et emails, nécessitant un effort manuel important pour produire des rapports fiables.',
 'Prospect describes data scattered in Excel, no single source of truth, slow ad-hoc reporting. Sample phrases: "our HR data is in Excel", "every report takes a week", "I don''t know my headcount right now", "we can''t trust the numbers".',
 'Employees', '(I21) * (I8) * (I15)', false),

('P07', 'hr_director', 'time', 8,
 'Manual time-off and holiday management across countries',
 'Gestión manual de vacaciones y ausencias entre países',
 'Gestion manuelle des congés et absences entre pays',
 'Manual leave tracking creates risk of payroll errors, employee disputes, and non-compliance with local labour regulations.',
 'El seguimiento manual de ausencias genera riesgo de errores en nómina, disputas y incumplimiento de regulaciones laborales locales.',
 'Le suivi manuel des congés crée des risques d''erreurs de paie, de litiges et de non-conformité aux réglementations locales.',
 'Prospect describes leave tracked in Excel, payroll errors from holidays, country-specific complexity. Sample phrases: "we manage holidays in Excel", "people fight over PTO balances", "leave handling differs per country", "time-off requests get lost".',
 'Time Off', '(I22) * (I8) * (I15)', false),

('P08', 'hr_director', 'inefficiency', 9,
 'High attrition without early disengagement signals',
 'Alta rotación sin señales tempranas de desvinculación',
 'Forte attrition sans signaux précoces de désengagement',
 'Disengagement is detected too late, so under-performers stay paid longer than necessary before action is taken.',
 'El desvinculamiento se detecta demasiado tarde, por lo que los empleados con bajo rendimiento siguen cobrando más tiempo del necesario.',
 'Le désengagement est détecté trop tard, les sous-performants restent payés plus longtemps que nécessaire avant toute action.',
 'Prospect describes surprise resignations, no eNPS, late discovery of disengagement. Sample phrases: "we lose key people without warning", "we don''t measure engagement", "I find out too late", "we keep paying people who already checked out".',
 'Surveys + Performance', '(I26) * (I17) * (I27) * (I1)', false),

('P09', 'hr_director', 'time', 10,
 'Slow onboarding extends time-to-productivity for new hires',
 'Un onboarding lento extiende el tiempo hasta la productividad de nuevas incorporaciones',
 'Un onboarding lent prolonge le délai de productivité des nouvelles recrues',
 'Lengthy onboarding delays new hire productivity, increasing payroll cost without corresponding output during ramp-up.',
 'Un onboarding largo retrasa la productividad, aumentando el coste de nómina sin producción correspondiente durante el ramp-up.',
 'Un onboarding long retarde la productivité, augmentant le coût salarial sans production correspondante pendant la montée en compétences.',
 'Prospect describes long ramp-up, paper-based onboarding, IT setup delays. Sample phrases: "new hires take months to be productive", "onboarding is a checklist in Excel", "IT setup is always late", "we don''t have a structured onboarding".',
 'Onboarding', '(I24) * (I10) * (I14) * (I3)', false),

('P10', 'hr_director', 'time', 11,
 'Slow, inconsistent performance review cycles',
 'Ciclos de evaluación del desempeño lentos e inconsistentes',
 'Cycles d''évaluation de la performance lents et incohérents',
 'Reviews are run manually in forms and spreadsheets, consuming manager time and limiting actionable feedback.',
 'Las evaluaciones se realizan manualmente en formularios y hojas de cálculo, consumiendo tiempo de los managers y limitando el feedback accionable.',
 'Les évaluations sont menées manuellement dans des formulaires et tableurs, consommant du temps managérial et limitant le feedback actionnable.',
 'Prospect describes review cycles in Word/Excel, missed deadlines, low completion. Sample phrases: "reviews are in Word", "managers hate review season", "we skip cycles", "no calibration across teams".',
 'Performance', '(I25) * (I13) * (I16)', false),

('P11a', 'hr_director', 'time', 12,
 'Slow, reactive HR reporting and analytics',
 'Reporting y analítica de RRHH lenta y reactiva',
 'Reporting et analytique RH lents et réactifs',
 'Every reporting request triggers manual Excel work, delaying decisions and consuming senior HR capacity.',
 'Cada solicitud de reporting dispara trabajo manual en Excel, retrasando decisiones y consumiendo capacidad senior de RRHH.',
 'Chaque demande de reporting déclenche du travail manuel Excel, retardant les décisions et consommant la capacité RH senior.',
 'Prospect describes board reports built manually, slow analytics requests. Sample phrases: "every board pack takes a week", "HR analytics is just Excel pivots", "I can''t slice headcount", "finance keeps asking for reports".',
 'Analytics', '(I23) * (I9) * (I15)', false),

('P11b', 'hr_director', 'time', 13,
 'Manual hiring process management eats recruiter time',
 'La gestión manual del proceso de contratación consume tiempo del recruiter',
 'La gestion manuelle du recrutement dévore le temps des recruteurs',
 'Recruiters and hiring managers waste hours scheduling interviews, screening candidates and chasing feedback without an integrated ATS.',
 'Los recruiters y hiring managers pierden horas programando entrevistas, filtrando candidatos y persiguiendo feedback sin un ATS integrado.',
 'Les recruteurs perdent des heures à planifier des entretiens, filtrer des candidats et relancer pour du feedback sans ATS intégré.',
 'Prospect describes interview scheduling chaos, candidates falling through, no ATS. Sample phrases: "we don''t have an ATS", "scheduling interviews is a nightmare", "I lose track of candidates", "we use email and Excel for hiring".',
 'Recruitment', '(I47) * (I3) * (I15)', false),

('P12', 'hr_director', 'direct_cost_saving', 14,
 'Leaky offboarding of people, assets and access',
 'Offboarding con fugas de personas, activos y accesos',
 'Offboarding défaillant : personnes, actifs et accès non récupérés',
 'Exits happen ad-hoc, leading to unrecovered equipment, persistent access and lost institutional knowledge.',
 'Las salidas ocurren de forma improvisada, dejando equipos sin recuperar, accesos persistentes y conocimiento institucional perdido.',
 'Les départs sont improvisés, entraînant des équipements non récupérés, des accès persistants et une perte de savoir institutionnel.',
 'Prospect describes lost laptops, persistent SaaS access after exits, no offboarding checklist. Sample phrases: "we always lose equipment", "access stays open after people leave", "offboarding is improvised", "IT and HR don''t coordinate on exits".',
 'Offboarding', '(I4) * (I35)', false),

('P13', 'hr_director', 'direct_cost_saving', 15,
 'Unstructured hiring leads to costly mis-hires',
 'Contratación sin estructura lleva a costosas malas contrataciones',
 'Recrutement non structuré mène à des erreurs de recrutement coûteuses',
 'Hiring without structured assessments and scorecards results in mis-hires that drain productivity and require costly replacements.',
 'Contratar sin evaluaciones estructuradas ni scorecards resulta en malas contrataciones que drenan productividad y requieren costosas sustituciones.',
 'Recruter sans évaluations structurées ni scorecards entraîne des erreurs de recrutement qui drainent la productivité et nécessitent des remplacements coûteux.',
 'Prospect describes gut-feel hiring, no scorecards, high probation failure. Sample phrases: "we hire on gut feeling", "half our hires don''t pass probation", "every manager interviews differently", "no structured assessments".',
 'Recruitment', '(I30) * (I31)', false),

('P14', 'hr_director', 'inefficiency', 16,
 'Limited performance data slows talent interventions',
 'Datos de rendimiento limitados ralentizan las intervenciones de talento',
 'Des données de performance limitées ralentissent les interventions sur les talents',
 'Without reliable performance data, coaching, promotions and role changes are delayed, reducing operational efficiency across the workforce.',
 'Sin datos de rendimiento fiables, el coaching, promociones y cambios de rol se retrasan, reduciendo la eficiencia operativa de la plantilla.',
 'Sans données de performance fiables, le coaching, les promotions et les changements de rôle sont retardés, réduisant l''efficacité opérationnelle.',
 'Prospect describes weak managers without coaching, slow promotions, no data-driven role changes. Sample phrases: "we have low performers we can''t act on", "promotions are political", "I have no data to coach managers", "role changes take forever".',
 'Performance', '(I28) * (I29) * (I1) * (I18)', false),

('P15', 'finance', 'time', 17,
 'Slow, manual expense reporting and reconciliation',
 'Reportes de gastos manuales y reconciliación lenta',
 'Rapports de dépenses manuels et réconciliation lente',
 'Manual expense reporting consumes finance hours every month and creates reimbursement reconciliation gaps.',
 'Los reportes manuales de gastos consumen horas de finanzas cada mes y crean discrepancias en la reconciliación de reembolsos.',
 'Les rapports de dépenses manuels consomment des heures de finance chaque mois et créent des écarts de réconciliation.',
 'Prospect describes paper receipts, finance reconciliation pain, employee complaints on reimbursements. Sample phrases: "expenses are in Excel", "finance spends days reconciling", "people complain about reimbursements", "we don''t see real-time spend".',
 'Expenses', '(I36) * (I9) * (I15)', false),

('P16', 'finance', 'inefficiency', 18,
 'Uncontrolled procurement spend and approval bypassing',
 'Gasto en compras descontrolado y aprobaciones evitadas',
 'Dépenses d''approvisionnement non contrôlées et contournement des approbations',
 'Off-process purchases escape approval workflows and budget control, inflating annual procurement costs.',
 'Las compras fuera de proceso escapan de los workflows de aprobación y del control presupuestario, inflando los costes anuales.',
 'Les achats hors processus échappent aux workflows d''approbation et au contrôle budgétaire, gonflant les coûts annuels.',
 'Prospect describes off-process purchases, no PO workflow, maverick spend. Sample phrases: "people buy outside the system", "we have no spend control", "POs are bypassed", "I don''t know what I''m spending".',
 'Spend Management', '(I37) * (I38) * (I1)', false),

('P17', 'finance', 'time', 19,
 'Manual payroll reconciliation consumes HR and finance time',
 'La reconciliación manual de nómina consume tiempo de RRHH y finanzas',
 'La réconciliation manuelle de la paie consomme du temps RH et finance',
 'Each payroll cycle requires manual checks and reconciliations across systems, consuming substantial HR and finance hours every month.',
 'Cada ciclo de nómina requiere verificaciones manuales y reconciliaciones entre sistemas, consumiendo horas significativas de RRHH y finanzas cada mes.',
 'Chaque cycle de paie nécessite des vérifications manuelles et réconciliations entre systèmes, consommant des heures significatives chaque mois.',
 'Prospect describes long payroll close, manual reconciliation across systems, HR/Finance overtime. Sample phrases: "payroll takes a week every month", "we re-key data into payroll", "HR and finance both touch payroll", "payroll close is always painful".',
 'Payroll', '(I39) * (I12) * (I15)', false),

('P18', 'finance', 'direct_cost_saving', 20,
 'Payroll errors create rework, disputes and compliance risk',
 'Errores de nómina generan retrabajo, disputas y riesgo de cumplimiento',
 'Les erreurs de paie créent du retravail, des litiges et un risque de conformité',
 'Manual reconciliation generates payroll errors that require corrections, employee disputes and compliance exposure each cycle.',
 'La reconciliación manual genera errores de nómina que requieren correcciones, disputas con empleados y exposición de cumplimiento cada ciclo.',
 'La réconciliation manuelle génère des erreurs de paie nécessitant des corrections, des litiges employés et une exposition à la conformité.',
 'Prospect describes recurring payroll errors, payslip complaints, manual corrections. Sample phrases: "we make payroll errors every month", "people complain about wrong payslips", "we always have corrections", "audit found payroll issues".',
 'Payroll', '(I40) * (I1) * (I41)', false),

('P19', 'finance', 'inefficiency', 21,
 'Compensation budget drifts off-plan annually',
 'El presupuesto de compensación se desvía del plan anualmente',
 'Le budget de rémunération dérive du plan annuellement',
 'Merit, promotion and bonus cycles run in Excel, allowing total comp to exceed budget without controls.',
 'Los ciclos de mérito, promoción y bonus se ejecutan en Excel, permitiendo que la compensación total exceda el presupuesto sin controles.',
 'Les cycles de mérite, promotion et bonus sont gérés en Excel, permettant à la rémunération totale de dépasser le budget sans contrôle.',
 'Prospect describes Excel-based comp cycles, comp drift over budget, no controls during merit. Sample phrases: "comp cycle is Excel chaos", "we always over-spend on bonuses", "managers approve raises ad-hoc", "I lost track of total comp".',
 'Compensation', '(I1) * (I18) * (I42)', false),

('P20', 'finance', 'inefficiency', 22,
 'No project-level cost visibility hides unprofitable work',
 'Sin visibilidad de costes por proyecto se oculta trabajo no rentable',
 'L''absence de visibilité des coûts par projet masque le travail non rentable',
 'Without project-level time and cost data, leaders cannot identify low-margin or loss-making projects, eroding overall profitability.',
 'Sin datos de tiempo y coste a nivel de proyecto, los líderes no pueden identificar proyectos con bajo margen, erosionando la rentabilidad.',
 'Sans données de temps et de coûts au niveau projet, les dirigeants ne peuvent identifier les projets déficitaires, érodant la rentabilité.',
 'Prospect describes no time-to-project allocation, gut-feel project margins. Sample phrases: "we don''t track time per project", "I don''t know which clients are profitable", "project margins are a guess", "we accept work without margin analysis".',
 'Projects', '(I45) * (I46)', false),

('P21', 'c_level', 'direct_cost_saving', 23,
 'Unmanaged software licenses and access rights',
 'Licencias de software no gestionadas y derechos de acceso descontrolados',
 'Licences logicielles non gérées et droits d''accès non contrôlés',
 'Unused SaaS licenses inflate cost per employee, while orphan accounts after offboarding create a security risk.',
 'Las licencias SaaS sin usar inflan el coste por empleado, mientras que las cuentas huérfanas tras el offboarding crean riesgo de seguridad.',
 'Les licences SaaS inutilisées gonflent le coût par employé, tandis que les comptes orphelins après offboarding créent un risque de sécurité.',
 'Prospect describes orphan SaaS accounts, unused licenses, no central inventory, or license sprawl. Sample phrases: "we pay for tools nobody uses", "orphan accounts after exits", "IT can''t see who has what", "license sprawl".',
 'IT Hub', '(I43) * (I1)', false),

('P22', 'c_level', 'direct_cost_saving', 24,
 'Multi-country HR setup prevents consolidation',
 'Configuración de RRHH multi-país impide la consolidación',
 'Configuration RH multi-pays empêche la consolidation',
 'Each country runs its own tools and processes, preventing global policies and economies of scale.',
 'Cada país ejecuta sus propias herramientas y procesos, impidiendo políticas globales y economías de escala.',
 'Chaque pays utilise ses propres outils et processus, empêchant les politiques globales et les économies d''échelle.',
 'Prospect operates in 2+ countries, runs different HR tools per entity, can''t consolidate reporting. Sample phrases: "each country has its own HR system", "I can''t get a global headcount", "tooling cost per entity adds up", "we duplicate processes per country".',
 'Multi-entity', '(I2) * (I44)', false);

-- Insert formula variables (49 inputs)
INSERT INTO pain_formula_vars (var_key, pain_id, label_en, label_es, label_fr, unit, default_value_es, default_value_fr, default_value_other, source, auto_manual, sort_order, is_headline) VALUES
('I1', 'P01', 'Number of employees', 'Número de empleados', 'Nombre d''employés', 'count', NULL, NULL, NULL, 'prospect', 'automatic', 1, true),
('I2', 'P22', 'Number of countries / entities', 'Número de países / entidades', 'Nombre de pays / entités', 'count', 2, 2, 2, 'user_input', 'manual', 2, true),
('I3', 'P09', 'Hires per year', 'Contrataciones por año', 'Embauches par an', 'count', 2, 2, 2, 'user_input', 'manual', 3, true),
('I4', 'P12', 'Annual leavers', 'Bajas anuales', 'Départs annuels', 'count', 2, 2, 2, 'user_input', 'manual', 4, true),
('I5', 'P05b', 'Documents signed per year', 'Documentos firmados por año', 'Documents signés par an', 'count', 200, 200, 200, 'user_input', 'automatic', 5, false),
('I6', 'P20', 'Projects per year', 'Proyectos por año', 'Projets par an', 'count', 5, 5, 5, 'user_input', 'manual', 6, false),
('I7', 'P01', 'Work days per year', 'Días laborales por año', 'Jours ouvrés par an', 'days', 220, 225, 230, 'user_input', 'automatic', 7, false),
('I8', 'P06', 'Weeks per year', 'Semanas por año', 'Semaines par an', 'weeks', 52, 52, 52, 'user_input', 'automatic', 8, false),
('I9', 'P04', 'Months per year', 'Meses por año', 'Mois par an', 'count', 12, 12, 12, 'user_input', 'automatic', 9, false),
('I10', 'P09', 'Working hours per day', 'Horas de trabajo por día', 'Heures de travail par jour', 'h', 8, 7, 8, 'user_input', 'automatic', 10, false),
('I11', 'P02', 'Annual working hours', 'Horas de trabajo anuales', 'Heures de travail annuelles', 'h', 1800, 1600, 1800, 'user_input', 'automatic', 11, false),
('I12', 'P17', 'Payroll runs per year', 'Nóminas procesadas por año', 'Cycles de paie par an', 'count', 12, 12, 12, 'user_input', 'automatic', 12, false),
('I13', 'P10', 'Review cycles per year', 'Ciclos de evaluación por año', 'Cycles d''évaluation par an', 'count', 2, 2, 2, 'user_input', 'automatic', 13, false),
('I14', 'P01', 'Loaded hourly cost — Employee', 'Coste hora cargado — Empleado', 'Coût horaire chargé — Employé', 'EUR/h', 25, 35, 30, 'user_input', 'automatic', 14, false),
('I15', 'P06', 'Loaded hourly cost — HR / Finance specialist', 'Coste hora cargado — Especialista RRHH / Finanzas', 'Coût horaire chargé — Spécialiste RH / Finance', 'EUR/h', 35, 45, 40, 'user_input', 'automatic', 15, false),
('I16', 'P04', 'Loaded hourly cost — Manager', 'Coste hora cargado — Manager', 'Coût horaire chargé — Manager', 'EUR/h', 39, 50, 45, 'user_input', 'automatic', 16, false),
('I17', 'P08', 'Loaded monthly cost — Employee', 'Coste mensual cargado — Empleado', 'Coût mensuel chargé — Employé', 'EUR/month', 4000, 5000, 4500, 'user_input', 'automatic', 17, false),
('I18', 'P14', 'Loaded annual cost per employee', 'Coste anual cargado por empleado', 'Coût annuel chargé par employé', 'EUR', 48000, 60000, 54000, 'user_input', 'automatic', 18, false),
('I19', 'P01', 'Minutes saved per employee/day on time tracking', 'Minutos ahorrados por empleado/día en control horario', 'Minutes économisées par employé/jour sur le suivi du temps', 'min/day', 10, 10, 10, 'user_input', 'manual', 19, true),
('I20', 'P02', 'Over/under-staffing reduction', 'Reducción de sobre/sub-dotación', 'Réduction du sur/sous-effectif', '%', 0.03, 0.03, 0.03, 'user_input', 'manual', 20, true),
('I21', 'P06', 'HR ops hours/week saved', 'Horas/semana ahorradas en ops RRHH', 'Heures/semaine économisées en ops RH', 'h/week', 3, 3, 3, 'user_input', 'manual', 21, true),
('I22', 'P07', 'Hours/week saved on leave management', 'Horas/semana ahorradas en gestión de ausencias', 'Heures/semaine économisées en gestion des congés', 'h/week', 4, 4, 4, 'user_input', 'manual', 22, true),
('I23', 'P11a', 'Hours saved per month on reporting', 'Horas ahorradas al mes en reporting', 'Heures économisées par mois en reporting', 'h', 8, 8, 8, 'user_input', 'manual', 23, true),
('I24', 'P09', 'Days saved on time-to-productivity per new hire', 'Días ahorrados en tiempo-hasta-productividad por nueva incorporación', 'Jours économisés sur le temps de productivité par nouvelle recrue', 'days', 30, 30, 30, 'user_input', 'manual', 24, true),
('I25', 'P10', 'Manager hours saved per review cycle', 'Horas de manager ahorradas por ciclo de evaluación', 'Heures manager économisées par cycle d''évaluation', 'h', 4, 4, 4, 'user_input', 'manual', 25, true),
('I26', 'P08', 'Months delay avoided before acting on under-performance', 'Meses de retraso evitados antes de actuar sobre bajo rendimiento', 'Mois de retard évités avant d''agir sur la sous-performance', 'months', 4, 4, 4, 'user_input', 'manual', 26, true),
('I27', 'P08', '% of employees impacted by performance / engagement issues per year', '% de empleados afectados por problemas de rendimiento / engagement al año', '% d''employés impactés par des problèmes de performance / engagement par an', '%', 0.05, 0.05, 0.05, 'user_input', 'manual', 27, false),
('I28', 'P14', 'Productivity uplift per intervention', 'Aumento de productividad por intervención', 'Gain de productivité par intervention', '% pts', 0.15, 0.15, 0.15, 'user_input', 'manual', 28, true),
('I29', 'P14', 'Employees with performance intervention per year', 'Empleados con intervención de rendimiento por año', 'Employés avec intervention de performance par an', '%', 0.10, 0.10, 0.10, 'user_input', 'manual', 29, false),
('I30', 'P13', 'Mis-hires avoided per year', 'Malas contrataciones evitadas por año', 'Erreurs de recrutement évitées par an', 'count', 2, 2, 2, 'user_input', 'manual', 30, true),
('I31', 'P13', 'Cost per mis-hire', 'Coste por mala contratación', 'Coût par erreur de recrutement', 'EUR', 25000, 35000, 30000, 'user_input', 'manual', 31, false),
('I32', 'P03', 'Training subsidy captured per employee/year', 'Subvención de formación capturada por empleado/año', 'Subvention formation captée par employé/an', 'EUR', 80, 120, 50, 'user_input', 'manual', 32, true),
('I33', 'P04', 'Hours saved per month on training admin', 'Horas ahorradas al mes en administración de formación', 'Heures économisées par mois en admin formation', 'h', 6, 6, 6, 'user_input', 'manual', 33, true),
('I34', 'P05b', 'Minutes saved per document', 'Minutos ahorrados por documento', 'Minutes économisées par document', 'min', 30, 30, 30, 'user_input', 'manual', 34, true),
('I35', 'P12', 'Asset / license value recovered per leaver', 'Valor de activos / licencias recuperados por baja', 'Valeur actifs / licences récupérée par départ', 'EUR', 350, 400, 400, 'user_input', 'manual', 35, true),
('I36', 'P15', 'Hours saved per month on expense reporting', 'Horas ahorradas al mes en reporting de gastos', 'Heures économisées par mois en rapports de dépenses', 'h', 12, 12, 12, 'user_input', 'manual', 36, true),
('I37', 'P16', 'Maverick spend capture rate', 'Tasa de captura de gasto descontrolado', 'Taux de capture des achats sauvages', '%', 0.04, 0.04, 0.04, 'user_input', 'manual', 37, true),
('I38', 'P16', 'Annual procurable spend per employee', 'Gasto anual aprovisionable por empleado', 'Dépense annuelle approvisionnée par employé', 'EUR', 10000, 12000, 11000, 'user_input', 'manual', 38, false),
('I39', 'P17', 'Hours saved per payroll run', 'Horas ahorradas por ciclo de nómina', 'Heures économisées par cycle de paie', 'h', 8, 10, 9, 'user_input', 'manual', 39, true),
('I40', 'P18', '% of employees with at least 1 payroll error per year', '% de empleados con al menos 1 error de nómina al año', '% d''employés avec au moins 1 erreur de paie par an', '%', 0.20, 0.18, 0.19, 'user_input', 'manual', 40, true),
('I41', 'P18', 'Cost per payroll error', 'Coste por error de nómina', 'Coût par erreur de paie', 'EUR', 200, 250, 225, 'user_input', 'manual', 41, false),
('I42', 'P19', '% compensation budget drift avoided', '% de desvío de presupuesto de compensación evitado', '% de dérive budgétaire de rémunération évitée', '%', 0.01, 0.01, 0.01, 'user_input', 'manual', 42, true),
('I43', 'P21', 'License waste saved per employee/year', 'Gasto en licencias recuperado por empleado/año', 'Gaspillage licences économisé par employé/an', 'EUR', 150, 180, 160, 'user_input', 'manual', 43, true),
('I44', 'P22', 'Duplicated tooling cost per entity/year', 'Coste de herramientas duplicadas por entidad/año', 'Coût d''outillage dupliqué par entité/an', 'EUR', 8000, 9000, 8500, 'user_input', 'manual', 44, true),
('I45', 'P20', 'Unprofitable projects identified per year', 'Proyectos no rentables identificados por año', 'Projets non rentables identifiés par an', 'count', 3, 3, 3, 'user_input', 'manual', 45, true),
('I46', 'P20', 'Avg loss avoided per unprofitable project', 'Pérdida media evitada por proyecto no rentable', 'Perte moyenne évitée par projet non rentable', 'EUR', 10000, 12000, 11000, 'user_input', 'manual', 46, false),
('I47', 'P11b', 'Hours saved per hire on process management', 'Horas ahorradas por contratación en gestión del proceso', 'Heures économisées par embauche en gestion du processus', 'h', 10, 10, 10, 'user_input', 'manual', 47, true),
('I48', 'P05a', 'Hours saved per training created', 'Horas ahorradas por formación creada', 'Heures économisées par formation créée', 'h', 8, 8, 8, 'user_input', 'manual', 48, true),
('I49', 'P05a', 'Trainings created per year', 'Formaciones creadas por año', 'Formations créées par an', 'count', 12, 12, 12, 'user_input', 'automatic', 49, false);
