UPDATE pain_library SET pain_statement_es = 'Control horario manual y riesgo de inspección' WHERE pain_id = 'P01';
UPDATE pain_library SET pain_statement_es = 'Planificación de turnos ineficiente y desperdicio de nómina' WHERE pain_id = 'P02';
UPDATE pain_library SET pain_statement_es = 'Selección lenta y dependencia de agencias' WHERE pain_id = 'P03';
UPDATE pain_library SET pain_statement_es = 'Registros de formación dispersos y subvenciones perdidas' WHERE pain_id = 'P04';
UPDATE pain_library SET pain_statement_es = 'Consultas repetitivas saturan a RRHH' WHERE pain_id = 'P05';
UPDATE pain_library SET pain_statement_es = 'Firma manual de contratos y documentos' WHERE pain_id = 'P06';
UPDATE pain_library SET pain_statement_es = 'Visibilidad limitada de datos de RRHH en tiempo real' WHERE pain_id = 'P07';
UPDATE pain_library SET pain_statement_es = 'Gestión manual de vacaciones y ausencias' WHERE pain_id = 'P08';
UPDATE pain_library SET pain_statement_es = 'Alta rotación sin señales tempranas de desvinculación' WHERE pain_id = 'P09';
UPDATE pain_library SET pain_statement_es = 'Onboarding lento retrasa la productividad' WHERE pain_id = 'P10';
UPDATE pain_library SET pain_statement_es = 'Ciclos de evaluación lentos e inconsistentes' WHERE pain_id = 'P11';
UPDATE pain_library SET pain_statement_es = 'Sin pulso continuo de engagement ni eNPS' WHERE pain_id = 'P12';
UPDATE pain_library SET pain_statement_es = 'Decisiones salariales sin datos ni equidad' WHERE pain_id = 'P13';
UPDATE pain_library SET pain_statement_es = 'Reporting de RRHH lento y reactivo' WHERE pain_id = 'P14';
UPDATE pain_library SET pain_statement_es = 'Offboarding sin control de equipos ni accesos' WHERE pain_id = 'P15';
UPDATE pain_library SET pain_statement_es = 'Informes de gastos manuales y reconciliación lenta' WHERE pain_id = 'P16';
UPDATE pain_library SET pain_statement_es = 'Gasto en compras sin control ni aprobación' WHERE pain_id = 'P17';
UPDATE pain_library SET pain_statement_es = 'Reconciliación de nómina manual con errores frecuentes' WHERE pain_id = 'P18';
UPDATE pain_library SET pain_statement_es = 'Presupuesto de compensación se desvía del plan' WHERE pain_id = 'P19';
UPDATE pain_library SET pain_statement_es = 'Licencias software y accesos sin gestionar' WHERE pain_id = 'P20';

UPDATE pain_library SET pain_statement_fr = 'Suivi du temps manuel et risque d''inspection' WHERE pain_id = 'P01';
UPDATE pain_library SET pain_statement_fr = 'Planification des shifts inefficace et gaspillage de paie' WHERE pain_id = 'P02';
UPDATE pain_library SET pain_statement_fr = 'Recrutement lent et dépendance aux agences' WHERE pain_id = 'P03';
UPDATE pain_library SET pain_statement_fr = 'Dossiers de formation dispersés et subventions perdues' WHERE pain_id = 'P04';
UPDATE pain_library SET pain_statement_fr = 'Questions répétitives submergent les RH' WHERE pain_id = 'P05';
UPDATE pain_library SET pain_statement_fr = 'Signature manuelle des contrats et documents' WHERE pain_id = 'P06';
UPDATE pain_library SET pain_statement_fr = 'Visibilité limitée des données RH en temps réel' WHERE pain_id = 'P07';
UPDATE pain_library SET pain_statement_fr = 'Gestion manuelle des congés et absences' WHERE pain_id = 'P08';
UPDATE pain_library SET pain_statement_fr = 'Attrition élevée sans signaux précoces de désengagement' WHERE pain_id = 'P09';
UPDATE pain_library SET pain_statement_fr = 'Onboarding lent retarde la productivité' WHERE pain_id = 'P10';
UPDATE pain_library SET pain_statement_fr = 'Cycles d''évaluation lents et incohérents' WHERE pain_id = 'P11';
UPDATE pain_library SET pain_statement_fr = 'Pas de pulse continu d''engagement ni eNPS' WHERE pain_id = 'P12';
UPDATE pain_library SET pain_statement_fr = 'Décisions salariales sans données ni équité' WHERE pain_id = 'P13';
UPDATE pain_library SET pain_statement_fr = 'Reporting RH lent et réactif' WHERE pain_id = 'P14';
UPDATE pain_library SET pain_statement_fr = 'Offboarding sans contrôle des équipements ni accès' WHERE pain_id = 'P15';
UPDATE pain_library SET pain_statement_fr = 'Notes de frais manuelles et réconciliation lente' WHERE pain_id = 'P16';
UPDATE pain_library SET pain_statement_fr = 'Dépenses d''achat sans contrôle ni approbation' WHERE pain_id = 'P17';
UPDATE pain_library SET pain_statement_fr = 'Réconciliation de paie manuelle avec erreurs fréquentes' WHERE pain_id = 'P18';
UPDATE pain_library SET pain_statement_fr = 'Budget de compensation dévie du plan annuel' WHERE pain_id = 'P19';
UPDATE pain_library SET pain_statement_fr = 'Licences logicielles et accès non gérés' WHERE pain_id = 'P20';